# Generated from .\antlr\ltl.g4 by ANTLR 4.7.2
from antlr4 import *
if __name__ is not None and "." in __name__:
    from .ltlParser import ltlParser
else:
    from ltlParser import ltlParser

'''
Auto-generated by ANTLR4. Please check ltl.g4 for grammar details.
'''


# This class defines a complete listener for a parse tree produced by ltlParser.
class ltlListener(ParseTreeListener):

    # Enter a parse tree produced by ltlParser#unaryExpr.
    def enterUnaryExpr(self, ctx:ltlParser.UnaryExprContext):
        pass

    # Exit a parse tree produced by ltlParser#unaryExpr.
    def exitUnaryExpr(self, ctx:ltlParser.UnaryExprContext):
        pass


    # Enter a parse tree produced by ltlParser#parFormula.
    def enterParFormula(self, ctx:ltlParser.ParFormulaContext):
        pass

    # Exit a parse tree produced by ltlParser#parFormula.
    def exitParFormula(self, ctx:ltlParser.ParFormulaContext):
        pass


    # Enter a parse tree produced by ltlParser#binaryExpr.
    def enterBinaryExpr(self, ctx:ltlParser.BinaryExprContext):
        pass

    # Exit a parse tree produced by ltlParser#binaryExpr.
    def exitBinaryExpr(self, ctx:ltlParser.BinaryExprContext):
        pass


    # Enter a parse tree produced by ltlParser#ap.
    def enterAp(self, ctx:ltlParser.ApContext):
        pass

    # Exit a parse tree produced by ltlParser#ap.
    def exitAp(self, ctx:ltlParser.ApContext):
        pass


